# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/configuration/all/
# -------------------------------------------------------------------------------------

# Website title.
title = ""
# Hostname (and path) to the root.
baseURL = "http://localhost:1313"
# Theme list.
# Enable in your site config file.
# theme = ["FixIt"]
# Determines default content language.
# available values: ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"
# Language code.
# available values: ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# Language name.
# available values: ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"
# Whether to include Chinese/Japanese/Korean.
hasCJKLanguage = false
# Timezone local.
# timeZone = "Asia/Shanghai"
# Copyright description used only for SEO schema.
copyright = ""
# Whether to use robots.txt.
enableRobotsTXT = true
# Whether to use git commit log.
enableGitInfo = true
# Whether to use emoji code.
enableEmoji = true
# The capitalization rules to follow.
# available values: ["ap", "chicago", "go", "firstupper", "none"]
titleCaseStyle = "ap"
# Whether to capitalize automatic list titles.
capitalizeListTitles = false
# The main sections of a site.
# If set, the MainSections method on the Site object returns the given sections,
# otherwise it returns the section with the most pages.
# mainSections = ["posts"]
# The editor to use when creating new content.
# newContentEditor = "code"
# Ignore some build warnings and errors.
ignoreLogs = []
